package networking;

public enum CommandType {
    TERMINATE_CONN ("TERMINATE_CONN"),
    JOIN_GAME ("JOIN_GAME"),
    PLAYER_JOINED ("PLAYER_JOINED"),
    JOIN_GAME_RESP ("JOIN_GAME_RESP"),
    GAME_START ("GAME_START"),
    DIAG_OFFER ("DIAG_OFFER"),
    DIAG_RESP ("DIAG_RESP"),
    GAME_START_MULLIGAN ("GAME_START_MULLIGAN"),
    GAME_START_ACCEPT ("GAME_START_ACCEPT"),
    SHUFFLE_DECK ("SHUFFLE_DECK"),
    RETURN_CARD ("RETURN_CARD"),
    PLAY_CARD ("PLAY_CARD"),
    PLAY_CARD_RESP ("PLAY_CARD_RESP"),
    GAME_END ("GAME_END"),
    TURN_START ("TURN_START"),
    TURN_END ("TURN_END"),
    DRAW_CARD ("DRAW_CARD"),
    DRAW_CARD_RESP ("DRAW_CARD_RESP"),
    DRAW_CARD_RESP_OPP ("DRAW_CARD_RESP_OPP"),
    DESTROY_CARD ("DESTROY_CARD"),
    ATTACK_CARD ("ATTACK_CARD"),
    ACTIVATE_TRICKSTER ("ACTIVATE_TRICKSTER"),
    ALLOW_ACTION ("ALLOW_ACTION"),
    DESTROY_CARD_RESP ("DESTROY_CARD_RESP"),
    LEVEL_MAGE ("LEVEL_MAGE"),
    LEVEL_MAGE_RESP ("LEVEL_MAGE_RESP"),
    CHOOSE_COST ("CHOOSE_COST"),
    CHOOSE_COST_RESP ("CHOOSE_COST_RESP"),
    TARGET_CARD ("TARGET_CARD"),
    TARGET_CARD_RESP ("TARGET_CARD_RESP"),
    MOVE_CARD ("MOVE_CARD"),
    SPAWN_CASTLES("SPAWN"),
    CASTLE_DAMAGE("CASTLE_DAMAGE");
    private String stringValue;
    CommandType(String toString) {
        stringValue = toString;
    }

    @Override
    public String toString() {
        return stringValue;
    }
}
